controllers/SiteController.php
<?php

namespace app\controllers;

use app\models\AppealForm;
use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\Response;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use app\models\RegForm;

class SiteController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout', 'salary', 'appeals', 'bonuses', 'instructions', 'best'],
                'rules' => [
                    [
                        'actions' => ['logout', 'salary', 'appeals', 'bonuses', 'instructions', 'best'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        if (Yii::$app->user->isGuest) {
            $this->layout = 'anonymous';
            return $this->render('index');
        } else {
            return $this->render('main');
        }
    }

    /**
     * Reg action.
     *
     * @return Response|string
     */
    public function actionReg()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $this->layout = 'anonymous';

        $model = new RegForm();
        if ($model->load(Yii::$app->request->post())) {
            if ($user = $model->reg()) {
                if (Yii::$app->user->login($user)) {
                    return $this->goHome();
                }
            }
        }

        $model->password = '';
        $model->password_repeat = '';
        return $this->render('reg', [
            'model' => $model,
        ]);
    }

    /**
     * Login action.
     *
     * @return Response|string
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $this->layout = 'anonymous';

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        }

        $model->password = '';
        return $this->render('login', [
            'model' => $model,
        ]);
    }

    /**
     * Logout action.
     *
     * @return Response
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    public function actionSalary()
    {
        return $this->render('salary');
    }

    public function actionAppeals()
    {
        $model = new AppealForm();
        $isSend = false;

        if ($model->load(Yii::$app->request->post()) && $model->send()) {
            $isSend = true;
            $model->reason = '';
            $model->to = '';
            $model->text = '';
            $model->isAnonymous = '';
        }

        return $this->render('appeals', [
            'model' => $model,
            'isSend' => $isSend,
        ]);
    }

    public function actionBonuses()
    {
        return $this->render('bonuses');
    }

    public function actionInstructions()
    {
        return $this->render('instructions');
    }

    public function actionBest()
    {
        return $this->render('best');
    }
}

views/site/appeals.php
<?php

/* @var $this yii\web\View */
/* @var $model app\models\AppealForm */
/* @var $isSend bool */

use yii\helpers\Url;
use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Обращения к руководству';
?>
<div class="container">
    <br>
    <p><b><?=Yii::$app->user->identity->name?></b>, вы перешли на страницу обращения к руководству, здесь вы можете написать жалобу/просьбу или сообщить о какой-либо ситуации, произошедшей во время рабочего процесса.</p>
    <p>Вы можете оставить анонимное или персональное обращение.</p>

    <?php if ($isSend): ?>
    <div class="alert alert-success" style="margin-top: 5vh;">
        <strong>Обращение успешно отправлено!</strong>
    </div>
    <?php endif; ?>

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'reason')->textInput(['autofocus' => true])->label($model->attributeLabels()['reason'] . ':') ?>

    <?= $form->field($model, 'to')->textInput()->label($model->attributeLabels()['to'] . ':') ?>

    <?= $form->field($model, 'text')->textarea()->label($model->attributeLabels()['text'] . ':') ?>

    <?= $form->field($model, 'isAnonymous')->label('')->inline()->radioList([1 => 'Анонимное', 0 => 'Персональное'], ['separator' => '&nbsp;&nbsp;&nbsp;']); ?>

    <?= Html::submitButton('Отправить', ['class' => 'btn btn-primary', 'name' => 'login-button']) ?>

    <?php ActiveForm::end(); ?>

    <br>
    <br>
    <br>
    <br>
</div>

views/site/best.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Url;
use yii\helpers\Html;

$this->title = 'Лучшие сотрудники';
?>
<div class="container">
    <h4>Лучшие работники месяца</h4>
    <div class ="row">

        <div class="col-md-3 ">

            <div class="card" style="width:270px; height:400px;">
                <img class="card-img-top"src ="img/img_avatar1.png" alt="Card image" style="width:100%; height:55%;">
                <div class="card-body">
                    <h5 class="card-title">Петров Петр Петрович</h5>
                    <p>Должность:</p>
                    <p>Цех:</p>
                    <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#myModal">
                        Посмотреть профиль
                    </button>
                </div>
            </div>
        </div>
        <div class="col-md-3 ">

            <div class="card" style="width:270px; height:400px;">
                <img class="card-img-top"src ="img/img_avatar1.png" alt="Card image" style="width:100%; height:55%;">
                <div class="card-body">
                    <h5 class="card-title">Петров Петр Петрович</h5>
                    <p>Должность:</p>
                    <p>Цех:</p>
                    <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#myModal">
                        Посмотреть профиль
                    </button>
                </div>
            </div>
        </div>
        <div class="col-md-3">

            <div class="card" style="width:270px; height:400px;">
                <img class="card-img-top"src ="img/img_avatar1.png" alt="Card image" style="width:100%; height:55%;">
                <div class="card-body">
                    <h5 class="card-title">Петров Петр Петрович</h5>
                    <p>Должность:</p>
                    <p>Цех:</p>
                    <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#myModal">
                        Посмотреть профиль
                    </button>
                </div>
            </div>
        </div>
        <div class="col-md-3">

            <div class="card" style="width:270px; height:400px;">
                <img class="card-img-top"src ="img/img_avatar1.png" alt="Card image" style="width:100%; height:55%;">
                <div class="card-body">
                    <h5 class="card-title">Петров Петр Петрович</h5>
                    <p>Должность:</p>
                    <p>Цех:</p>
                    <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#myModal">
                        Посмотреть профиль
                    </button>
                </div>
            </div>
        </div>
        <div class="col-md-3">

            <div class="card" style="width:270px; height:400px;">
                <img class="card-img-top"src ="img/img_avatar1.png" alt="Card image" style="width:100%; height:55%;">
                <div class="card-body">
                    <h5 class="card-title">Петров Петр Петрович</h5>
                    <p>Должность:</p>
                    <p>Цех:</p>
                    <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#myModal">
                        Посмотреть профиль
                    </button>
                </div>
            </div>
        </div>
        <div class="col-md-3 ">

            <div class="card" style="width:270px; height:400px;">
                <img class="card-img-top"src ="img/img_avatar1.png" alt="Card image" style="width:100%; height:55%;">
                <div class="card-body">
                    <h5 class="card-title">Петров Петр Петрович</h5>
                    <p>Должность:</p>
                    <p>Цех:</p>
                    <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#myModal">
                        Посмотреть профиль
                    </button>
                </div>
            </div>
        </div>
        <div class="col-md-3">

            <div class="card" style="width:270px; height:400px;">
                <img class="card-img-top"src ="img/img_avatar1.png" alt="Card image" style="width:100%; height:55%;">
                <div class="card-body">
                    <h5 class="card-title">Петров Петр Петрович</h5>
                    <p>Должность:</p>
                    <p>Цех:</p>
                    <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#myModal">
                        Посмотреть профиль
                    </button>
                </div>
            </div>
        </div>
        <div class="col-md-3">

            <div class="card" style="width:270px; height:400px;">
                <img class="card-img-top"src ="img/img_avatar1.png" alt="Card image" style="width:100%; height:55%;">
                <div class="card-body">
                    <h5 class="card-title">Петров Петр Петрович</h5>
                    <p>Должность:</p>
                    <p>Цех:</p>
                    <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#myModal">
                        Посмотреть профиль
                    </button>
                </div>
            </div>
        </div>
    </div>
</div>

views/site/bonuses.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Url;
use yii\helpers\Html;

$this->title = 'Система бонусов';
?>
<div class="container">
    <div class="alert alert-success" style="margin-top: 5vh;">
        <strong>Username, вы приветсвуем вас в системе бонусов на данный момент у вас имеется n баллов!  Выберете награду из списка.</strong>
    </div>
    <h5> Выберете награду из списка</h5>
    <h6> У вас на счету: N баллов!</h6>
    <div class = "row">
        <div class="col-md-3">
            <div class="card" style="width:270px; height:400px;">
                <img class="card-img-top"src ="img/3.jpg" alt="Card image" style="width:100%; height:55%;">
                <div class="card-body">
                    <h5 class="card-title">Выходной</h5>
                    <p>Cтоимость: N</p>
                    <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#myModal">
                        Выбрать награду
                    </button>
                </div>
            </div>
        </div>
        <div class="col-md-3">
            <div class="card" style="width:270px; height:400px;">
                <img class="card-img-top"src ="img/4.jpg" alt="Card image" style="width:100%; height:55%;">
                <div class="card-body">
                    <h5 class="card-title">Аванс</h5>
                    <p>Cтоимость: N</p>
                    <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#myModal">
                        Выбрать награду
                    </button>
                </div>
            </div>
        </div>
        <div class="col-md-3">
            <div class="card" style="width:270px; height:400px;">
                <img class="card-img-top"src ="img/2.jpg" alt="Card image" style="width:100%; height:55%;">
                <div class="card-body">
                    <h5 class="card-title">Внеочередной отпуск</h5>
                    <p>Cтоимость: N</p>
                    <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#myModal">
                        Выбрать награду
                    </button>
                </div>
            </div>
        </div>
        <div class="col-md-3">
            <div class="card" style="width:270px; height:400px;">
                <img class="card-img-top"src ="img/1.jpg" alt="Card image" style="width:100%; height:55%;">
                <div class="card-body">
                    <h5 class="card-title">Доп.премия к зарплате</h5>
                    <p>Cтоимость: N</p>
                    <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#myModal">
                        Выбрать награду
                    </button>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="myModal">
    <div class="modal-dialog">
        <div class="modal-content">

            <!-- Modal Header -->
            <div class="modal-header">
                <h4 class="modal-title">Ваша награда успешно выбрана!</h4>
                <button type="button" class="close" data-dismiss="modal">×</button>
            </div>

            <!-- Modal body -->
            <div class="modal-body">
                Распечатайте пожалуйста данную выписку и по приходу на работу предьявите начальству.
            </div>
        </div>
    </div>
</div>

views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

views/site/index.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Url;

$this->title = 'Приветствие';
?>
<link rel="stylesheet" href="log_style.css">

<div class="container">
    <div class="row">
        <div class="col-md-12">
            <center><h1>Добро пожаловать в BrestmashWebapp, пожалуйста, зарегистируйтесь или авторизуйтесь</h1></center>
        </div>
    </div>
    <div class="row justify-content-center">
        <div class="col-lg-4">
            <a href ="<?=Url::toRoute(['/site/login']) ?>">  <button type="button" class="btn btn-info">Авторизация</button></a>
            <a href="<?=Url::toRoute(['/site/reg']) ?>"> <button type="button" class="btn btn-primary">Регистрация</button></a>
        </div>
    </div>
</div>

views/site/instructions.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Url;
use yii\helpers\Html;

$this->title = 'Инструкции';
?>
<div class="container">
    <p>В разработке...</p>

</div>

views/site/login.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\LoginForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Авторизация';
?>
<link rel="stylesheet" href="log_style.css">
<div class="container">
    <div class="row justify-content-center">
        <div class="col-lg-4">
            <h2>Авторизация</h2>
            <?php $form = ActiveForm::begin(); ?>

            <?= $form->field($model, 'number')->textInput(['autofocus' => true])->label('Табельный номер:') ?>

            <?= $form->field($model, 'password')->passwordInput()->label('Пароль:') ?>

            <?= $form->field($model, 'rememberMe')->checkbox()->label('Запомнить меня') ?>

            <?= Html::submitButton('Войти', ['class' => 'btn btn-primary', 'name' => 'login-button']) ?>

            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>

views/site/main.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Url;
use yii\helpers\Html;

$this->title = 'Главная';
?>
<div class="employee_card" style="margin-top: 5vh;">
    <div class="container">
        <div class="row align-items-center">
            <div class="col-lg-4">
                <h4>Добро пожаловать!</h4>
                <div class="card" style="width:280px; height:400px;">
                    <img class="card-img-top"src ="img/img_avatar1.png" alt="Card image" style="width:100%">
                    <div class="card-body">
                        <h5 class="card-title"><?=Yii::$app->user->identity->name?></h5>
                        <center>
                            <?=Html::beginForm(['/site/logout'], 'post')?>
                            <?=Html::submitButton(
                                'Выйти',
                                ['class' => 'btn btn-danger']
                            )?>
                            <?=Html::endForm()?>
                        </center>
                    </div>
                </div>
            </div>
            <div class="col-lg-7">
                <h4 style="margin-bottom: 15px;">Личная карта работника</h4>
                <div class="card_list">
                    <a href="#" class="list-group-item list-group-item-action"><h5>Табельный номер: <?=Yii::$app->user->identity->id?></h5></a>
                    <a href="#" class="list-group-item list-group-item-action"><h5>Должность: <?=Yii::$app->user->identity->getPosition()->name?></h5></a>
                    <a href="#" class="list-group-item list-group-item-action"><h5>Цех: <?=Yii::$app->user->identity->getManufactory()->name?></h5></a>
                    <a href="#" class="list-group-item list-group-item-action"><h5>Количество бонусов: <?=Yii::$app->user->identity->getBonus()->count?></h5></a>
                    <a href="#" class="list-group-item list-group-item-action"><h5>Cтаж работы: <?=Yii::$app->user->identity->getExpirience()?></h5></a>
                    <a href="#" class="list-group-item list-group-item-action"><h5>Дата рождения: <?=Yii::$app->user->identity->birthday?></h5></a>
                    <a href="#" class="list-group-item list-group-item-action"><h5>Рабочий график: <?=Yii::$app->user->identity->getSchedule()?></h5></a>
                </div>
            </div>
        </div>
    </div>
</div>

views/site/reg.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\RegForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Регистрация';
?>
<link rel="stylesheet" href="log_style.css">
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-4">
            <h2>Регистрация</h2>
            <?php $form = ActiveForm::begin(); ?>

            <?= $form->field($model, 'number')->textInput(['autofocus' => true])->label('Табельный номер:') ?>

            <?= $form->field($model, 'password')->passwordInput()->label('Пароль:') ?>

            <?= $form->field($model, 'password_repeat')->passwordInput()->label('Повторите пароль еще раз:') ?>

            <?= Html::submitButton('Зарегистрироваться!', ['class' => 'btn btn-primary', 'name' => 'reg-button']) ?>

            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>

views/site/salary.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Url;
use yii\helpers\Html;

$this->title = 'Расчет зарплаты';
?>
<div class="salaries_result" style="margin-top: 5vh;">
    <div class="container">
        <div class="alert alert-info">
            <b><?=Yii::$app->user->identity->name?>!</b> По вашему запросу был произведен расчет зарплаты за текущий месяц.
        </div>

        <?php if (Yii::$app->user->identity->getSalary()->hasHoursRebuke()): ?>
        <div class="alert alert-danger">
            <b><?=Yii::$app->user->identity->name?>!</b> Вас ждёт выговор от начальства за неотработанные часы.
        </div>
        <?php endif; ?>

        <?php if (Yii::$app->user->identity->getSalary()->hasPassRebuke()): ?>
        <div class="alert alert-danger">
            <b><?=Yii::$app->user->identity->name?>!</b> Вас ждёт выговор от начальства за пропуск по неуважительной причине.
        </div>
        <?php endif; ?>

        <h3><?=Yii::$app->user->identity->getSalary()->getCalcMonth()?></h3>

        <h4>Ваши рабочие показатели на текущий момент составляют:</h4>
        <div class="list-group">
            <h5 class="list-group-item list-group-item-action">Отработанных часов: <?=Yii::$app->user->identity->getSalary()->getWorkHours()?></h5>
            <h5 class="list-group-item list-group-item-action">Сделаных деталей: <?=Yii::$app->user->identity->getSalary()->getDoneParts()?></h5>
            <h5 class="list-group-item list-group-item-action">Прогулов по ув. причине: <?=Yii::$app->user->identity->getPass()->good_absence_count?></h5>
            <h5 class="list-group-item list-group-item-action">Прогулов по неув. причине: <?=Yii::$app->user->identity->getPass()->bad_absence_count?></h5>
            <h5 class="list-group-item list-group-item-action">Ваша зарплата составит: <?=Yii::$app->user->identity->getSalary()->getSum()?></h5>
            <h5 class="list-group-item list-group-item-action">Ваша премия составит: <?=Yii::$app->user->identity->getSalary()->getAward()?></h5>
            <h5 class="list-group-item list-group-item-action">Итого: <?=Yii::$app->user->identity->getSalary()->getTotal()?></h5>
        </div>
        <div class="alert alert-dark" style="margin-top: 10px;">
            Расчет зарплаты был произведен согласно сдельно-премиальной оплате труда
        </div>
        <div class="alert alert-warning">
            <strong>По всем вопросам обращайтесь к начальству или в бухгалтерию</strong>
        </div>
        <br>
        <br>
    </div>
</div>